# Generated by Django 4.1.5 on 2023-03-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickleModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickle_model", models.FileField(upload_to="")),
                ("username", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(default="Document name", max_length=255),
        ),
        migrations.AlterField(
            model_name="document",
            name="username",
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
