# Generated by Django 4.1.5 on 2023-03-06 20:12

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_picklemodels_alter_document_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picklemodels",
            name="pickle_model",
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
