# Generated by Django 4.1.5 on 2023-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_picklemodels_pickle_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picklemodels",
            name="pickle_model",
            field=models.FileField(upload_to=""),
        ),
    ]
